[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.26"
via_ir = true
optimizer = true
# optimizer_runs = 200
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "all"
sort_imports = true
line_length = 120

[profile.ci]
verbosity = 4

[rpc_endpoints]
holesky = "${HOLESKY_RPC_URL}"
neox_t4 = "${NEOX_T4_RPC_URL}"

[etherscan]
holesky = { key = "${HOLESKY_ETHERSCAN_API_KEY}"}

[profile.neox_t4]
chainId = 12227332
rpcUrl = "https://neoxt4seed1.ngd.network/"